PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE queue(id TEXT PRIMARY KEY, curr_pos INTEGER, owner TEXT);
INSERT INTO "queue" VALUES('foo', 0, 'foo');
INSERT INTO "queue" VALUES('bar', 0, 'bar');
CREATE TABLE queue_element(queue_id TEXT, pos INTEGER, owner TEXT, used_ts INTEGER);
INSERT INTO "queue_element" VALUES('foo',1,'owner1',NULL);
INSERT INTO "queue_element" VALUES('bar',1,'owner2',NULL);
INSERT INTO "queue_element" VALUES('foo',2,'owner3',NULL);
INSERT INTO "queue_element" VALUES('bar',2,'owner4',NULL);
INSERT INTO "queue_element" VALUES('foo',3,'owner5',NULL);
INSERT INTO "queue_element" VALUES('bar',3,'owner6',NULL);
COMMIT;